rules:
  - name: resource tagging
    resources:
      - aws_s3_bucket
      - aws_rds_cluster
    attributes:
      - name: "tags.Name"
        rules:
          - startsWith: "org-example-"
          - required: true
      - name: "tags.Environment"
        rules:
          - required: true
          - oneOf:
            - Development
            - Production
            - Staging
            - Test

approvals:
  - resources:
      - aws_iam_role
      - aws_iam_policy
      - aws_s3_bucket
    approvers:
      - jmccormick